In [2]:
import pandas as pd 
import numpy as np

df = pd.DataFrame({
    "user_id": [101,102, 103, 104, 105, 106, 107, 108],
    "age": [22, 35, 29, 41, 35, 27, 50, 31],
    "income": [8.0, 15.0, 10.0, 25.0, np.nan, 9.0, 40.0, 13.0],
    "treatment": [1, 0, 1, 0, 1, 1, 0, 1],
    "conversion": [0, 0, 1, 0, 0, 1, 1, 0]
})

In [ ]:
df["treatment"]
df[["treatment"]]

   treatment
0          1
1          0
2          1
3          0
4          1
5          1
6          0
7          1

In [8]:
df["treatment"]==1

0     True
1    False
2     True
3    False
4     True
5     True
6    False
7     True
Name: treatment, dtype: bool

In [9]:
df[df["treatment"] == 1]

   user_id  age  income  treatment  conversion
0      101   22     8.0          1           0
2      103   29    10.0          1           1
4      105   35     NaN          1           0
5      106   27     9.0          1           1
7      108   31    13.0          1           0

In [10]:
df[
    (df["treatment"] == 1)
    & (df["conversion"] == 1)
]

   user_id  age  income  treatment  conversion
2      103   29    10.0          1           1
5      106   27     9.0          1           1

In [13]:
df.loc[
    df["treatment"] == 1,
    ["age", "income"]
]

   age  income
0   22     8.0
2   29    10.0
4   35     NaN
5   27     9.0
7   31    13.0

In [14]:
df.iloc[2]

user_id       103.0
age            29.0
income         10.0
treatment       1.0
conversion      1.0
Name: 2, dtype: float64

In [15]:
df.loc[3]

user_id       104.0
age            41.0
income         25.0
treatment       0.0
conversion      0.0
Name: 3, dtype: float64